// define UI actions here

export default {
  TOGGLE_SCREENSHOT_MODE: 'TOGGLE_SCREENSHOT_MODE',
  TOGGLE_SCREENSHOT_CLIPPED_MODE: 'TOGGLE_SCREENSHOT_CLIPPED_MODE',
  START: 'START',
  STOP: 'STOP',
  CLEANUP: 'CLEANUP',
  PAUSE: 'PAUSE',
  UNPAUSE: 'UNPAUSE',
};
